server:
  port: 9000
  error:
    path: /exError
    whitelabel:
      enabled: false
      

spring:
  jwt:
    secret: $2a$10$Nz.2j8OVbxuo/taCTOVowu.A//Rr3163jJGs4cdj0vACLyvCnlCZ2
    refreshTokenSecret: (2a$10$Nz.4j8OVbxuo/taCTOVowu.A//Rr3163jJGs4cdj0vACLyvCnlCZ3

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:test
    username : sa
    password :
    initialization-mode: always

  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


springdoc:
  #packages-to-scan: org.api.sample.web
  swagger-ui:
    disable-swagger-default-url: true

  paths-to-match: /api/**


