DROP TABLE MEMBERS IF EXISTS;

CREATE TABLE MEMBERS (
    ID VARCHAR(100) PRIMARY KEY,
    PWD VARCHAR(256) NOT NULL
);

INSERT INTO MEMBERS (ID, PWD) VALUES
('test', '$2a$10$pHgCHsO5YqoowXnrJXn.M.Aulbe1yX19efxLiVaigv15QDJaK1guG'),
('test2', '$2a$10$pHgCHsO5YqoowXnrJXn.M.Aulbe1yX19efxLiVaigv15QDJaK1guG');

